### ISSUE TITLE
Pushmanager does not strip branch names

### ISSUE THREAD

**Issue by rschlaikjer** [Yelp/pushmanager#107]
When branch names are submitted to pushmanager, it does not strip trailing whitespace, which can lead to failures to parse revisions and fetch the branches.

**Comment by michalczapko** [comment]
Seems like this issue is fixed for new requests (sha: 341949535fd320fb376ce2a394ed5542227fbbd1). I've found the issue exists also when a new push is created, there is a fix for the other case: #153
