### ISSUE TITLE
Command window is too small

### ISSUE THREAD

**Issue by asottile** [Yelp/pushmanager#161]
![screen shot 2015-03-18 at 9 06 12 am](https://cloud.githubusercontent.com/assets/1810591/6713227/3e7f4c58-cd4e-11e4-9797-e2c4071019a1.png)

**Comment by milki** [comment]
Can you include OS and browser and version?

**Comment by asottile** [comment]
Firefox + (Windows 8 || Ubuntu 14.04)

**Comment by kkellyy** [comment]
This is actually fixed with #159 [here]( https://github.com/Yelp/pushmanager/blob/a371aea294fbb944caaf6b71e42010cc2136e2d4/pushmanager/static/js/push.js#L62). @chunkyg and I only saw it with the addition of the new button.
